config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'home/index'

  root 'home#index'

    authenticate :admin do
      resources :articles, only: [:new, :create, :edit, :update, :destroy] do
        resources :comments, only: [:edit, :update, :destroy]
      end
    end

    resources :articles, only: [:show, :index] do
      resources :comments, only: [:show, :index, :new, :create]
    end

    resources :tags, only: [:show, :index] do
      resources :articles, only: [:show, :index]
    end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_taggable
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def create
	  @article = Article.new(article_params)

	  if @article.save
	  	redirect_to @article
	  else
	  	render 'new'
	  end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end

	private
	  def article_params
	    params.require(:article).permit(:title, :text, :tag_list)
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		num_comments = @article.comments.length
		if num_comments <= 4
			@comment = @article.comments.create(comment_params)
		else
			flash[:max_comments] = "The maximum number of comments has been reached."
		end
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
		def comment_params
			params.require(:comment).permit(:name, :body)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Article.tag_counts
	end

	def show
		@tag = params[:id]
		@articles = Article.tagged_with(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<article class="Article">
    <img class="Article__previewImage" src="/images/iceland.jpg">
    <div class="Article__content">
        <h1 class="Article__title"><%= article.title %></h1>
        <% if list %>
            <p class="Article__blurb"><%= article.blurb %></p>
        <% end %>
        <div class="Article__meta">
            <div class="Article__edit">
                <img class="Article__icon" src="/images/topics.svg">
                <%= link_to(edit_article_path(article)) do %>
                    <h4 class="Article__attr">Edit</h4>
                <% end %>
                <%= link_to(article_path(article), method: :delete) do %>
                    <h4 class="Article__attr">Delete</h4>
                <% end %>
            </div>
            <div class="Article__tags">
                <img class="Article__icon" src="/images/tag.svg">
                <% article.tag_list.each_with_index do |tag, index| %>
                    <%= link_to(tag_path(tag)) do %>
                        <% if index == article.tag_list.size - 1%>
                         <h4 class="Article__attr"><%= tag %></h4>
                        <% else %>
                            <h4 class="Article__attr"><%= tag %>,</h4>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <div class="Article__time">
                <img class="Article__icon" src="/images/time.svg">
                <h4 class="Article__attr"><%= article.updated_at.strftime('%b %d, %Y') %></h4>
            </div>
        </div>
        <% if list %>
            <%= link_to(article_path(article)) do %>
                <button class="dark-white">
                    Read more
                </button>
            <% end %>
        <% else %>
            <% article.text.split("\n").each do |para| %>
                <p class="Article__body"><%= para %></p>
            <% end %>
        <% end %>
    </div>
</article>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Articles', articles_path %>

app/views/articles/index.html.erb
<% content_for :header do %>
    <title>RoR Blog</title>
<% end %>

<section class="Articles">
    <div class="Articles__list">
        <div class="Articles__header">
            <h1 class="Articles__title">My RoR Articles</h1>
        </div>
        <%= render :partial => 'article', :collection => @articles, :locals => {list: true} %>
    </div>
    <dir class="Articles__blank"></dir>
</section>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Articles', articles_path %>

app/views/articles/show.html.erb
<section class="Post">
    <div class="Post__content">
    	<%= render :partial => 'article', :locals => {list: false, article: @article} %>
    </div>
    <dir class="Post__blank"></dir>
</section>

<section class="Comments">
	<h2 class="Comments__title">Comments:</h2>
	<%= render @article.comments %>
	<% if flash[:max_comments] %>
		<p class="Utilities__notice"><%= flash[:max_comments] %></p>
	<% end %>
	<h5 class="Comments__add">Add a comment</h5>
	<%= render 'comments/form' %>
</section>

app/views/comments/_comment.html.erb
<div class="Comment">
	<p class="notice"></p>
	<h3 class="Comment__name"><%= comment.name %></h3>
	<p class="Comment__body"><%= comment.body %></p>
	<% if admin_signed_in? %>
		<p class="Comment__delete">
		  <%= link_to 'Delete Comment', article_comment_path(@article, comment),
		               method: :delete,
		               data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'Form__text' %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => 'Form__text' %>
  </p>
  <p>
    <%= f.submit 'Submit', :class => 'Form__whiteDark' %>
  </p>
<% end %>

app/views/home/index.html.erb
<div class="Home">
	<h1 class="Home__title Utilities__header">Welcome to my RoR blog!</h1>
	<p class="Home__para">For better or for worse this is <strong>not</strong> a real blog. You may read the lorem ipsum text if you like, but this site was created solely to demonstrate my RoR knowledge</p>
	<p class="Home__para">This site is built with Ruby on Rails and hosted with DigitalOcean, Unicorn, and Nginx.</p>
	<p class="Home__para">If you would like authentication credentials to create, edit, and delete articles, please <a class="Utilities__nakedLink" href="mailto:zackarey.thoutt@colorado.edu?Subject=RoR%20Blog%20Admin%20Access">request them.</a></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= yield :header %>

</head>
<body>
	<div id="content">
		<%= render "components/nav" %>
		<main>
			<%= yield %>
		</main>
	</div>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= yield :scripts %>

</body>
</html>

app/views/tags/index.html.erb
<div class="Utilities__header">
	<h1>The tag index!</h1>
</div>
<div class="Tags">
	<% @tags.each do |tag| %>
		<%= link_to(tag_path(tag.name)) do %>
			<h2 class="Tags__name">(<%= tag.count %>) <%= tag.name %></h2>
		<% end %>
	<% end %>
</div>

app/views/tags/show.html.erb
<section class="Articles">
    <div class="Articles__list">
        <div class="Articles__header">
            <h1 class="Articles__title"><%= @tag %> Articles</h1>
        </div>
        <%= render :partial => 'articles/article', :collection => @articles, :locals => {list: true} %>
    </div>
    <dir class="Articles__blank"></dir>
</section>